### ISSUE TITLE
All categories are not being displayed

### ISSUE THREAD

**Issue by kartikparmar** [TycheSoftwares/auto-add-to-cart-rules#8]
I have 20+ categories added in my setup but only two categories are getting displayed in the select2 dropdown.

Multiple Category's : 
![image](https://user-images.githubusercontent.com/15606823/73173797-331b1200-412c-11ea-9b4d-474e1f796122.png)

**Comment by Shasvat7** [comment]
Here it will display only the categories list which have products in it because our scenarios are based on the products of the categories..
